osx_image: xcode9.3
language: objective-c
xcode_project: Physical\ Time.xcodeproj
xcode_scheme: Physical\ Time
# Using xcodebuild instead of xctool. See https://stackoverflow.com/a/41797558
script:
    - xcodebuild clean build -sdk iphonesimulator -workspace Physical\ Time.xcworkspace -scheme Physical\ Time CODE_SIGNING_REQUIRED=NO
